const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const htmlPath = path.join(__dirname, "..", "policy", "index.html");
const cssPath = path.join(__dirname, "..", "policy", "assets", "policy.css");
const jsPath = path.join(__dirname, "..", "policy", "assets", "policy.js");
const html = fs.readFileSync(htmlPath, "utf8");
const css = fs.readFileSync(cssPath, "utf8");
const js = fs.readFileSync(jsPath, "utf8");
const visibleHtml = html.replace(/<script[\s\S]*?<\/script>/g, "");

assert.match(html, /src="\/src\/data\/policyService\.runtime\.js"/, "page should load policy runtime");
assert.match(html, /src="\/policy\/assets\/policy\.js"/, "page should load policy page script");
assert.match(html, /href="\/policy\/assets\/policy\.css"/, "page should load policy page CSS");
assert.match(visibleHtml, /养老8/);
assert.match(visibleHtml, /政策服务/);
assert.match(visibleHtml, /查查父母可能能享受哪些养老福利/);
assert.match(visibleHtml, /自助查询政策/);
assert.match(visibleHtml, /查看政策列表/);
assert.match(visibleHtml, /自助查询入口/);
assert.match(visibleHtml, /AI 帮你初筛和整理政策线索/);
assert.match(visibleHtml, /结果用于准备咨询材料，最终以当地窗口审核为准/);
assert.match(visibleHtml, /问题或关键词/);
assert.match(visibleHtml, /我爸82岁在长沙能领什么补贴/);
assert.match(html, /id="selfServiceQuery"/);
assert.match(html, /id="quickRegionSelect"/);
assert.match(html, /id="quickCategorySelect"/);
assert.match(html, /id="quickPolicySearchInput"/);
assert.match(html, /id="quickQueryBtn"/);
assert.match(html, /id="policyAiResult"/, "self-service query should expose an AI result area");
assert.match(visibleHtml, /政策项已接入/);
assert.match(visibleHtml, /当前查询地区：长沙/);
assert.match(visibleHtml, /北京/);
assert.match(visibleHtml, /上海/);
assert.match(visibleHtml, /全部地区/);
assert.match(visibleHtml, /正在读取政策项/);
assert.match(visibleHtml, /不承诺一定符合/);
assert.match(visibleHtml, /以当地审核为准/);
assert.match(visibleHtml, /官方来源可追溯/);
assert.match(visibleHtml, /直接按补贴类型查看政策项/);
assert.match(visibleHtml, /津贴和现金补贴/);
assert.match(visibleHtml, /失能照护和长护险/);
assert.match(visibleHtml, /其他养老支持/);
assert.match(visibleHtml, /不代表政府部门最终审核结果/);
assert.match(html, /id="policyBrowser"/);
assert.match(html, /id="policyDetailDrawer"/);
assert.doesNotMatch(html, /policyQuiz|policyResults|quizQuestion|quizNext|restartQuiz/, "page should not keep the removed questionnaire DOM");
assert.doesNotMatch(visibleHtml, /测评|帮父母测一测|回答几个问题|生成福利清单|第 1 题|下一题|重新测评/, "page should not expose questionnaire copy");
assert.doesNotMatch(html, /alert\s*\(/, "policy page should not use alert dialogs");
assert.doesNotMatch(visibleHtml, /MVP|Demo|demo|开发中|子站保留/, "page should not expose development wording");
assert.match(css, /--brand:\s*#075243/);
assert.match(css, /--radius:\s*8px/);
assert.match(css, /body\s*\{[\s\S]*background:\s*var\(--paper\)/);
assert.doesNotMatch(css, /quiz|meter|option-button|progress-card/, "CSS should not keep questionnaire selectors");
assert.doesNotMatch(css, /height:\s*100vh[\s\S]*overflow:\s*hidden/, "page should not use fixed viewport shells");
assert.match(css, /@media\s*\(max-width:\s*920px\)/, "mobile layout should be defined");
assert.match(js, /function renderPolicyList\(/, "browser should render policy cards");
assert.match(js, /function openPolicyDetail\(/, "policy detail drawer should be wired");
assert.match(js, /function showToast\(/, "page should use in-page toast feedback");
assert.match(js, /\/api\/policies/, "page should read policy items from the policies API");
assert.match(js, /\/api\/policy-query/, "self-service query should call the DeepSeek-backed policy query API");
assert.match(js, /normalizeSubsidyRow/, "page should normalize policy item fallback rows");
assert.match(js, /function applyQuickQuery\(/, "self-service query should update filters and list");
assert.match(js, /function fetchPolicyAiResult\(/, "self-service query should fetch AI policy guidance");
assert.match(js, /function renderPolicyAiResult\(/, "self-service query should render AI policy guidance");
assert.doesNotMatch(js, /当前条件没有匹配到可整理的政策项/, "self-service query should not short-circuit natural language keywords without local matches");
assert.doesNotMatch(js, /if\s*\(\s*!state\.policies\.length\s*\)/, "self-service query should call AI even when local policy candidates are empty");
assert.match(js, /scrollIntoView/, "self-service query should take users to the results");
assert.doesNotMatch(js, /renderQuestion|collectAnswer|renderResults|quiz|policyResults|生成福利清单|下一题/, "interaction script should not keep questionnaire behavior");
assert.doesNotMatch(js, /alert\s*\(/, "interaction script should not use alert dialogs");
assert.doesNotMatch(js, /确定符合|保证申请成功|一定可以领取/, "interaction copy should avoid certainty claims");
assert.match(css, /\.policy-ai-result/, "AI policy result should have page-level styling");

console.log("policy page static checks passed");
